### PR TITLE
#6 Added mermaid library to allow rendering diagrams within ig

### PR DESCRIPTION
**Pull request by aschuler84**
Added a dependency to the mermaid library, this allows for embedding uml and flow diagrams within an IG

In an IG instance, just include the following html element, and embed a mermaid.js diagram. For reference refer to https://mermaid.live/edit#pako:eNpVUclOwzAQ_RXLJ5C60ATSNgckmpZeikCiJ5IepvEktogXOQ5VleTfcVqEwCf7LTNPzy3NNUMa06LSp5yDdWS_zhTx5ylNuBW1k1AfyHj82G3REakVnjuyutlqUnNtjFDl7VW_GkQkaXeDDInjQn32Vyq5-F8VdmSd7sA4bQ5_mf1Jd2STijfux_9nuEXvek4LiAsY52BJAvZAR1SilSCYj94Ohow6jhIzGvurwsZZqDKaqd5LoXH6_axyGjvb4Ig2hoHDtYDSgvwPbphw2lK_q6o9WGlg6J8tdWcz1FT6QvzEXKtClAPe2MrD3DlTx9PpQE9K4XhznORaTmvBhk751zKaRkG0gCDEaB7CQxiy_DhbLorgflaw-d0sANr3I2pAfWgtfwPgJc_L9Y9-tvbfsPKOdA

 ```html
<pre class="mermaid">
  graph LR
    A --- B
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
</pre>
```

### CODE REVIEW

**Comment by gabriel0316** [comment]
Is this really necessary? PlantUML ist natively supported: https://fshschool.org/courses/fsh-seminar/02-creating-an-ig.html#recommended-tools-for-ig-authoring

**Comment by aschuler84** [comment]
> Is this really necessary? PlantUML ist natively supported: https://fshschool.org/courses/fsh-seminar/02-creating-an-ig.html#recommended-tools-for-ig-authoring

Oh nice, didn't know that - at least for the current version of our template it doesn't work. One more reason to update the template to a more recent version. 
In that case I will redo my commit and close this pull request.

**Comment by gabriel0316** [comment]
Interesting - I think I tried it once in TerminoloGit where we use a template that is based on this one, and it worked. Will have a look at it.

**Comment by aschuler84** [comment]
> Interesting - I think I tried it once in TerminoloGit where we use a template that is based on this one, and it worked. Will have a look at it.

I quickly looked into - this makes perfectly sense as the plant-uml from what I've discovered is integrated as a plugin in the Jekyll Template Engine. Hence, it depends on the version of IGPublisher being used and not so much on the template.

My suggestion ist to stick to the IGPublisher's feature with plant uml - so closing this.

**Comment by aschuler84** [comment]
Closing as does not apply

**Pull request closed without merging**
